id: I9E5C0945
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:48:13+00:00'
last_modified: '2022-06-07T12:32:06.629311+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD45157
  title: བསྟན་རིམ་ཆེན་མོ
  author: ''
  base:
    3D33:
      image_group_id: I2DB57598
      title: ''
      total_pages: 1048
      order: 1
      base_file: 3D33.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
