id: P000640
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD45157
  title: བསྟན་རིམ་ཆེན་མོ
  author: ''
  volumes:
    91735e3306e74d40aecd1a586953c919:
      image_group_id: I2DB57598
      title: ''
      volume_number: 1
      total_pages: 1048
